---

- name: ensure tasks run on the ansible container
  block:

    - name: display ovirt auth token
      ansible.builtin.debug:
        var: ovirt_auth
        verbosity: 1

    - name: release auth token
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent

  delegate_to: localhost

...
